# Generated by Django 5.2.6 on 2025-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoe'), ('jersey', 'Jersey'), ('equipment', 'Equipment')], max_length=100),
        ),
    ]
